### ISSUE TITLE
case sensitive scoring.

### ISSUE THREAD

**Issue by jcs090218** [lewang/flx#105]
If I have following code. It gave me a same score. Is there a way to identify the scoring engine with case sensitive? Thanks!

```el
(let ((str "lo"))
  (message "1. %s" (flx-score "log" str))
  (message "2. %s" (flx-score "Log" str)))
```

**Comment by oscarfv** [comment]
No without rewriting the hash function.

`flx` is somewhat case-sensitive. If you search for `Lo`, then `log` gives a 0 score. This is consistent with Emacs behavior, where searching (`C-s`) for `lo` finds both `log` and `Log`, but searching for `Lo` finds `Log` only.

`flx` does this intentionally (see function `flx-get-hash-for-string`).

**Comment by jcs090218** [comment]
I guess is a feature!? :) 

I am fine with it. Close this now! Thanks! 😄
