### ISSUE TITLE
Flip <fname>:<dir> with same name match

### ISSUE THREAD

**Issue by kootenpv** [lewang/flx#111]
So when I have 2 files with the same name,

```
folder_a/myfile.py
folder_b/myfile.py
```

I like that I can use `fola my` to match the first one.

However, when both are opened, this doesn't work anymore because I have the matches:

```
myfile.py:folder_a
myfile.py:folder_b
```

i.e. the fname and dir order gets changed

if I would be able to switch the structure to

```
folder_a:myfile.py
folder_b:myfile.py
```

for opened files, then I could still match using `fola my`

**Comment by oscarfv** [comment]
`flx` does not change how your buffers are named. You have some customization that causes that naming scheme.

Probably this: https://www.gnu.org/software/emacs/manual/html_node/emacs/Uniquify.html

Please close this issue if this answers your question.

**Comment by kootenpv** [comment]
@oscarfv thanks a lot for pointing me in the right direction, indeed I think uniquify is where I should be looking instead
