### ISSUE TITLE
Reference to free variable flx-ido-mode

### ISSUE THREAD

**Issue by lazywei** [lewang/flx#56]
Hi

I'm using el-get for flx and flx-ido. It works fine.
But I will get the warning everytime I install a new package:

```
Compiling no file at Tue Jun 17 00:12:53 2014
flx/flx-ido.elc:Warning: reference to free variable `flx-ido-mode'
```

It doesn't effect the functionalities of flx though.

**Comment by oscarfv** [comment]
Every time I start Emacs, a window pops up with

    Warning (bytecomp): reference to free variable ‘flx-ido-mode’ [5 times]

The advice about putting `(defvar flx-ido-mode)` or `(eval-when-compile (devar flx-ido-mode))` in `.emacs` before requiring the file didn't work. The warnings come from the uses of `flx-ido-mode` variable in `flx-ido.el`. It doesn't matter if `flx-ido.elc` exists or not.

I don't use the package system. `flx.el` and `flx-ido.el` are on a directory listed on `load-path`.

**Comment by lewang** [comment]
#80
