### ISSUE TITLE
On integrate flx with Helm

### ISSUE THREAD

**Issue by tuhdo** [lewang/flx#59]
Hi Le Wang,

This is my high level idea of how we could use `flx` for Helm. If it is not applicable, then I guess we can leave this an open issue that hopefully be solved in the future.

My idea is that, if we enter a bunch of patterns, some of which can be normal Helm pattern, some can be fuzzy pattern, then we divide the narrowing process into two phases:
- One is for normal Helm filtering. That is, we tried each pattern one by one; if one pattern results in empty set of candidates, then store that pattern and try the next one (without including the "failed" pattern). We filter until no more pattern and result in a set of candidates.
- One is for `flx` filtering. That is, we apply `flx` on the output from the above phases and narrow down further. The result of this phase is the final set to be returned to user.

The key point is that `flx` is only applied when a pattern can result in no candidate.

Thanks.

**Comment by PythonNut** [comment]
I think helm integration is addressed by [helm-flx](https://github.com/PythonNut/helm-flx/). If there are shortcomings in my implementation, feel free to open an issue there and we can talk discuss.
