### ISSUE TITLE
open directories

### ISSUE THREAD

**Issue by fommil** [lewang/flx#69]
Hi, thanks for this plugin. I just started using it with projectile and it's very nice.

I turned it on for all the things (all the global flags in the README) and although find-file was awesome, it couldn't work out how to open directories! Opening directories with find-file is a really key part of my workflow.

flx in find-file seems to be only trying to find files: how can I get it back so that directories appear in the list and pressing return on them will open them in dired?

**Comment by oscarfv** [comment]
`C-d`, navigate to the directory, select `.`, press `enter`.

Alternatively, `C-f`, navigate to the target directory, press `C-d`.

IIRC this is `ido` all the way, `flx` brings nothing new to the table.

**Comment by fommil** [comment]
Hmm. Maybe the wrong forum for this but can I make ido open directories with enter? These extra keys get in the way
