### ISSUE TITLE
Error on find file

### ISSUE THREAD

**Issue by wedens** [lewang/flx#79]
`flx-find-best-match: Variable binding depth exceeds max-specpdl-size`
I use flx with helm-flx.
/cc  @PythonNut

**Comment by PythonNut** [comment]
The simple solution is to throw this into your `init.el`:

```emacs
(setq max-lisp-eval-depth 5000
      max-specpdl-size 10000)
```
In general, those values are very reasonable on modern hardware.

The hard solution is to make `flx` do this for you automatically in an isolated manner.
