### ISSUE TITLE
Corner cases for Heuristics

### ISSUE THREAD

**Issue by EphramPerdition** [lewang/flx#81]
Corner cases seen while tweaking [helm-fuzzier](https://github.com/EphramPerdition/helm-fuzzier), for your consideration in tweaking the heuristics in flx. Probably More to come (There *was* a second example, but I've misplaced the note)

- `deft-filter` scores higher then `deft` for query `def`. (Need special case for single word candidates?)

**Comment by lewang** [comment]
This is expected.  It's my chosen balance between abbreviation and substring matches.  **de**f-**f**ilter is scored higher than **def**t.  However, if you continue typing "t", it should re-order.

**Comment by lewang** [comment]
The idea is if the current sort isn't exactly what you expect, continue typing along the lines you're thinking and your intentional target should continue to move up.

**Comment by EphramPerdition** [comment]
I know flx weights word beginnings heavily, I'm saying that breaks down for single word candidates.
You don't think `deft` is a "better" match for 'def' than for example `describe-font`?

**Comment by PythonNut** [comment]
@EphramPerdition in this case, it's not clear to me that `def` is a better match for `deft` than it is for `describe-font`. At least in my own usage, if I typed that, it could be either.

Granted, I have a pretty good understanding of the heuristics, so I generally craft queries to get what I want. 

However, there's at least one theoretical matter that's interesting. Le is correct in that fuzzy queries can always be extended if the matches are unsatisfactory. However, `describe-font` has *more room* to do so than `deft` does. Does that make `deft` a better candidate? Maybe. I don't know.

**Comment by lewang** [comment]
> You don't think deft is a "better" match for 'def' than for example describe-font?

I don't.  Otherwise I would give continuity a higher score  :) .  

In this case, if you press "t" after "def", it immediately scores higher due to being an exact match.

**Comment by EphramPerdition** [comment]
> I don't. Otherwise I would give continuity a higher score :) . 

:)  Heuristics are just another word for "personal taste".

Personally, I read "more room" as "less specific" and consider `decipher` `deft` and `debug` far better matches for `de` then  `diary-insert-entry` `diary-insert-cyclic-entry` `diary-yearly-entry` `diary-insert-block-entry` and the other 70 or so entries which flx ranks as "better". 

Of course that's not a "universal truth", just a matter of taste.

Here's how I modified my local flx to behave the way I like:
```elisp
(setq flx-word-separators '(?- ?\ ?_ ?: ?. ?/ ?\\)) ; - needs to be first, it ends up inside a regex []
(setq flx-word-separators-string (concat flx-word-separators))

(defun flx-score (str query &optional cache)
<...>
            ;; This is the computed score, adjusted to boost the scores
            ;; of exact matches.
            (if (or
                 (string-match
                  (format "\\(^%s[^%s]*$\\)" query flx-word-separators-string)
                  str)
                 (and full-match-boost
                      (=  (length (caar optimal-match))
                          (length str))))
                (+ (cl-cadar optimal-match) 10000)
              (cl-cadar optimal-match))
<...>
```

Now when I enter `de` as a query the first 3 hits are `decipher` `debug` and `deft`nstead of them appearing at the bottom of the list (this is with the latest `helm-fuzzier` of course).

**Comment by EphramPerdition** [comment]
As @PythonNut suggests, there's the issue of a certain prefix having very poor "selectivity", so if interpreting a contiguous group brings up a lot of `foo-thing1` `foo-thing2` `foo-thing3` and so on, it might be nice to boost results which are not "boilerplate matches" in that sense. 

Not sure how to formally describe the predicate that singles out such matches. flx is good enough, that's just an interesting idea to play with.

**Comment by oscarfv** [comment]
> in this case, it's not clear to me that def is a better match for deft than it is for describe-font. At least in my own usage, if I typed that, it could be either.

+1. It could be either, but I prefer `describe-font` as the first candidate.

The heuristics require some time to get accustomed to, but then you know what to type to arrive at the desired result quicker. There is no "always perfect" solution, though.
