### ISSUE TITLE
Bring flx support to auto-complete/popup 

### ISSUE THREAD

**Issue by ancane** [lewang/flx#84]
Hi. I'd like to bring flx match support to [popup menus](https://github.com/auto-complete/popup-el).
I got draft implementation [here](https://github.com/ancane/flx-popup). It's a lot like flx-ido, except some propertizing tweeks and duplicates tolerance. Is it OK to put `flx-popup` package here? Thanks.

**Comment by PythonNut** [comment]
@ancane I can't speak for @lewang, but is there any reason you'd like to track the code here instead of in your own repo? As the maintainer of `company-flx`, I'd suggest that having your own issue tracker and history is definitely a good thing.

**Comment by ancane** [comment]
@PythonNut Thanks. I guess you are right, I'll keep it in separate repo :+1:
