### ISSUE TITLE
disable until N characters for some completions

### ISSUE THREAD

**Issue by fommil** [lewang/flx#85]
I have some **huge** completion tables, and I don't want to be completing until I hit N (probably 3 or 4) characters when there are more than M (probably 50,000) total candidates. Is that possible?

**Comment by PythonNut** [comment]
Sure it's possible. Similar arrangements have been implemented in other packages that interface with `flx`. However, since `flx` does not expose functions for working on collections, what do you want us to do?

**Comment by fommil** [comment]
It's specifically the use of `projectile-completing-read`, are you saying that support would need to be implemented there rather than in `flx`? I had a look at their code and I can't see how it would be possible to do it there, they are just using standard `ido` and I had thought that `flx-ido` was intercepting those calls. I would expect that whatever hook is replacing `ido` with `flx-ido` would be able to do this bypass.

You say you don't work with collections, but don't you take some kind a collection as input?

**Comment by PythonNut** [comment]
@fommil wait, if you're talking about `flx-ido` then is the variable `flx-ido-limit` not enough? Limiting by number of candidates rather than input characters seems more correct.

**Comment by fommil** [comment]
are you sure about that? Typo maybe?

**Comment by fommil** [comment]
`flx-ido-threshold` ... ok! I'll try that on Monday

**Comment by PythonNut** [comment]
Sorry about that. I'm traveling and mostly posting from memory.

**Comment by fommil** [comment]
ok, this does actually help things... thanks!
