### ISSUE TITLE
flx-ido not support word beginnings match for C-h v (describe-variable)

### ISSUE THREAD

**Issue by zw963** [lewang/flx#88]
If worked with ![ido-ubiquitous](https://github.com/DarwinAwardWinner/ido-ubiquitous), it can support
`(describe-variable)` ido complete.

But, in this case,  word beginnings match is not worked.

Because another package, ![smex](https://github.com/nonsequitur/smex) work well, work well with
`M-x`, so I create issue here. 

if fix need made at ido-ubiquitous, I will made a issue there.

Thanks.

**Comment by lewang** [comment]
Can you give some detailed repro steps?  Also what you see and what you expect to see?

**Comment by zw963** [comment]
Sorry for confuse, It worked now with following config:

```cl
(require 'ido)
(require 'ido-ubiquitous)
(require 'flx-ido)

(ido-mode t)
(ido-everywhere t)
(ido-ubiquitous-mode 1)
(flx-ido-mode t)
```

And then, press `C-h v`.
