### ISSUE TITLE
it will crash my emacs

### ISSUE THREAD

**Issue by redguardtoo** [lewang/flx#9]
emacs 24.2.1, here is my .emacs.d: https://github.com/redguardtoo/emacs.d, I install the flx.el and flx-ido.el into my ~/.emacs.d/site-lisp/flx/ and configure it as README said.

Then when I run smex by pressing "M-x", emacs hang and quit, I think the key issue is the matching algorithm is too slow. maybe you should start your match algorithm since the first three key press.

**Comment by lewang** [comment]
no new info in a while.

**Comment by jasonm23** [comment]
These cleared up after Emacs 24.5.x
