### ISSUE TITLE
higher score to shorter strings

### ISSUE THREAD

**Issue by fommil** [lewang/flx#90]
I'd be interested in tuning the algorithm to give a slightly higher score to shorter strings that match (or conversely, penalising longer strings).

Where would I start?

Typicaly usecase is that when I search for something such as `ss` intending to match a file called `SearchService.scala` in my codebase, the hits for `SearchServiceSpec.scala` and `SearchServiceFixture.scala` are coming up first.

**Comment by ibrahima** [comment]
I also notice this a lot in my Rails projects, this would be a pretty good change to make I think. I guess with any type of fuzzy weighting system sometimes it's hard to predict how changes to the weights will behave in practice though...

**Comment by jtbm37** [comment]
This would be very much appreciated. Here is a very obvious example:
`(flx-score "StopMonitoringSubscriptionProcessorTests" "ms")`
gives (159 4 14)
`(flx-score "mstest.log" "ms")`
gives (140 0 1)

**Comment by oscarfv** [comment]
@jtbm37 : I think that your example is unrelated to the original report. What you want is prefix (or substring) matching which is precisely what `flx` is not about. There are packages that offer a matching system similar to what you want.

In your example, I want to see `StopMonitoringSubscriptionProcessorTests` placed before `mstest.log`. That's what I expect as a long time `flx` user.

**Comment by jtbm37** [comment]
@oscarfv I can only agree since after re-reading the package description it says clearly `The longer the substring match, the higher it scores. This maps well to how we think about matching.`

**Comment by fommil** [comment]
I think the example is exactly what my original post was about.

**Comment by oscarfv** [comment]
@fommll: are you sure? jtbm37's example is about substring matching (as he acknowledged on his last follow-up) while yours is about candidate length sorting (to which the rule quoted by jtbm37 also applies, although at times it seems counter-intuitive, but this is a problem with "magic" algorithms in general: when they give a result that you don't like, you end thinking that something is wrong, while not realizing that it is impossible to do all the time what every user expects.)

**Comment by jtbm37** [comment]
In my example I wanted to highlight the fact that the shorter the distance between 'm' and 's' is the higher it should score.

**Comment by fommil** [comment]
@oscarfv yes, I am sure. I want an option for shorter strings to weigh more, it's not about substring matching.
