### ISSUE TITLE
Surprising preference given to abbreviation match over an exact prefix

### ISSUE THREAD

**Issue by cubranic** [lewang/flx#91]
With `flx-ido` active, I try to open a file with `ido-find-file` and start typing "doc". Of the two possible matches in the current directory, "dh-ocr" and "Documents", "dh-ocr" is matched first. Shouldn't matching the prefix be given preference here?

**Comment by lewang** [comment]
Continuous matches score high, but abbreviation matches also score high.  That's the trade off in deciding to accomodate both.  Enter more characters to boost the match you have in mind.
